deployment:
  enabled: true
  replicas: 2

service:
  enabled: true
  type: LoadBalancer

ingressClass:
  enabled: true
  isDefaultClass: false
  name: traefik-shoplite

ports:
  web:
    expose:
      default: true
    exposedPort: 80
  websecure:
    expose:
      default: true
    exposedPort: 443
    tls:
      enabled: true
