apiVersion: v1
kind: ConfigMap
metadata:
  name: shoplite-frontend-config
  namespace: shoplite-stage
  labels:
    {{- include "shoplite.labels" . | nindent 4 }}
    component: frontend
data:
  PORT: "3000"
  API_BASE_URL: "https://api.stage.shoplite.local"
