apiVersion: v1
kind: ConfigMap
metadata:
  name: shoplite-product-service-config
  namespace: shoplite-stage
  labels:
    {{- include "shoplite.labels" . | nindent 4 }}
    component: product-service
data:
  SERVICE_NAME: "shoplite-product-service"
  PORT: "3000"
  CURRENCY: "USD"
