apiVersion: v1
kind: ConfigMap
metadata:
  name: shoplite-global-config
  namespace: shoplite-sandbox
  labels:
    {{- include "shoplite.labels" . | nindent 4 }}
    scope: global
data:
  APP_NAME: "ShopLite"
  APP_ENV: "stage"
  LOG_LEVEL: "info"
  OTEL_RESOURCE_ATTRIBUTES: "service.namespace=shoplite-sandbox,deployment.environment=sandbox"
  TEAM: "platform-devops"
