apiVersion: v1
kind: ConfigMap
metadata:
  name: shoplite-order-service-config
  namespace: shoplite-sandbox
  labels:
    {{- include "shoplite.labels" . | nindent 4 }}
    component: order-service
data:
  SERVICE_NAME: "shoplite-order-service"
  PORT: "3001"
  PRODUCT_SERVICE_TIMEOUT_MS: "5000"
