apiVersion: v1
kind: ConfigMap
metadata:
  name: shoplite-inventory-service-config
  namespace: shoplite-sandbox
  labels:
    {{- include "shoplite.labels" . | nindent 4 }}
    component: inventory-service
data:
  SERVICE_NAME: "shoplite-inventory-service"
  PORT: "3002"
  LOW_STOCK_THRESHOLD: "5"
