apiVersion: v1
kind: ConfigMap
metadata:
  name: shoplite-frontend-config
  namespace: shoplite-sandbox
  labels:
    {{- include "shoplite.labels" . | nindent 4 }}
    component: frontend
data:
  PORT: "3000"
  VITE_PRODUCT_SERVICE_URL: "http://shoplite-product-service"
  VITE_ORDER_SERVICE_URL: "http://shoplite-order-service"
  VITE_INVENTORY_SERVICE_URL: "http://shoplite-inventory-service"
