name: shoplite-frontend
namespace: shoplite-stage

labels:
  app: shoplite-frontend
  application: shoplite
  team: frontend
  app.kubernetes.io/part-of: shoplite
  app.kubernetes.io/instance: stage

annotations:
  reloader.stakater.com/auto: "true"

replicaCount: 1

image:
  repository: ghcr.io/shoplite-project/shoplite-frontend-service
  tag: stage-latest
  pullPolicy: Always

envFromConfigMaps:
  - shoplite-global-config
  - shoplite-stage-config
  - shoplite-frontend-config

containerPort: 80

service:
  enabled: true
  type: ClusterIP
  port: 80
  targetPort: 80

livenessProbe:
  enabled: true
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 15
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  enabled: true
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3
  successThreshold: 1

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

autoscaling:
  enabled: false

serviceAccount:
  create: true

ingress:
  enabled: false
